"""empty message

Revision ID: 49e57bcaed3d
Revises: 6047e736bb7e
Create Date: 2020-03-06 15:59:54.601238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e57bcaed3d'
down_revision = '6047e736bb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa',
    sa.Column('id_pagamento', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=True),
    sa.Column('moeda', sa.Integer(), nullable=True),
    sa.Column('valor_pago', sa.Integer(), nullable=True),
    sa.Column('valor_produto', sa.Integer(), nullable=True),
    sa.Column('troco', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_pagamento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('caixa')
    # ### end Alembic commands ###
